# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dr', max_length=20, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(default=0, null=True)),
                ('specialty', models.CharField(default='Physician', max_length=200)),
                ('hospital', models.CharField(default='kikuyu Hospital', max_length=200)),
                ('profile_photo', models.ImageField(default='doc_profiles/no-image.jpg', upload_to='doc_profiles/')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
