# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20180320_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.IntegerField(default=254)),
                ('gender', models.CharField(max_length=6)),
                ('id_number', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=5)),
                ('profile_photo', models.ImageField(null=True, upload_to='patients_photo/')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Doctor')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
