# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_given', models.DateTimeField()),
                ('doctor_prescribed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Medicine'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.NextOfKin'),
        ),
    ]
