# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20180322_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nhif_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
